CREATE USER abix_dbo    WITH ENCRYPTED PASSWORD 'Abix.44';
CREATE DATABASE abix_db WITH OWNER abix_dbo;
GRANT ALL PRIVILEGES ON DATABASE abix_db TO abix_dbo;
CREATE USER abix_access WITH ENCRYPTED PASSWORD 'Abix.44';
GRANT ALL PRIVILEGES ON DATABASE abix_db TO abix_access;
